/* Generated by Yosys 0.59+110 (git sha1 8ea51e147, clang++ 18.1.8 -fPIC -O3) */

(* top =  1  *)
(* src = "test_simple.v:4.1-36.10" *)
module test_simple(clk, a, b, c, d, out1, out2);
  (* src = "test_simple.v:5.16-5.19" *)
  input clk;
  wire clk;
  (* src = "test_simple.v:6.16-6.17" *)
  input a;
  wire a;
  (* src = "test_simple.v:7.16-7.17" *)
  input b;
  wire b;
  (* src = "test_simple.v:8.16-8.17" *)
  input c;
  wire c;
  (* src = "test_simple.v:9.21-9.22" *)
  input [7:0] d;
  wire [7:0] d;
  (* src = "test_simple.v:10.17-10.21" *)
  output out1;
  wire out1;
  (* src = "test_simple.v:11.17-11.21" *)
  output out2;
  wire out2;
  (* src = "test_simple.v:34.25-34.27|redstone_techmap.v:252.26-252.27" *)
  wire [0:0] _0_;
  (* src = "test_simple.v:16.6-16.12" *)
  wire and_ab;
  (* src = "test_simple.v:19.5-19.12" *)
  wire dff_out;
  (* src = "test_simple.v:15.6-15.11" *)
  wire not_a;
  (* src = "test_simple.v:17.6-17.11" *)
  wire or_bc;
  (* src = "test_simple.v:18.6-18.16" *)
  wire xor_result;
  (* src = "test_simple.v:28.1-30.4" *)
  DFF _1_ (
    .C(clk),
    .D(xor_result),
    .Q(dff_out)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "test_simple.v:23.17-23.22|simple_map.v:2.44-2.83" *)
  AND _2_ (
    .A(a),
    .B(b),
    .Y(and_ab)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "test_simple.v:24.16-24.21|simple_map.v:3.42-3.81" *)
  OR _3_ (
    .A(b),
    .B(c),
    .Y(or_bc)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "test_simple.v:25.21-25.35|simple_map.v:4.44-4.83" *)
  XOR _4_ (
    .A(and_ab),
    .B(or_bc),
    .Y(xor_result)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "test_simple.v:33.15-33.30|simple_map.v:2.44-2.83" *)
  AND _5_ (
    .A(not_a),
    .B(dff_out),
    .Y(out1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "test_simple.v:34.15-34.27|simple_map.v:4.44-4.83" *)
  XOR _6_ (
    .A(dff_out),
    .B(_0_),
    .Y(out2)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "test_simple.v:22.16-22.18|simple_map.v:1.41-1.73" *)
  NOT _7_ (
    .A(a),
    .Y(not_a)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "test_simple.v:34.25-34.27|redstone_techmap.v:256.27-256.59" *)
  RS_REDUCE_AND _8_ (
    .A(d),
    .Y(_0_)
  );
endmodule
