/* Generated by Yosys 0.59+110 (git sha1 8ea51e147, clang++ 18.1.8 -fPIC -O3) */

(* top =  1  *)
(* src = "test_simple.v:4.1-35.10" *)
module test_simple(clk, a, b, c, out1, out2);
  (* src = "test_simple.v:5.16-5.19" *)
  input clk;
  wire clk;
  (* src = "test_simple.v:6.16-6.17" *)
  input a;
  wire a;
  (* src = "test_simple.v:7.16-7.17" *)
  input b;
  wire b;
  (* src = "test_simple.v:8.16-8.17" *)
  input c;
  wire c;
  (* src = "test_simple.v:9.17-9.21" *)
  output out1;
  wire out1;
  (* src = "test_simple.v:10.17-10.21" *)
  output out2;
  wire out2;
  (* src = "test_simple.v:15.6-15.12" *)
  wire and_ab;
  (* src = "test_simple.v:18.5-18.12" *)
  wire dff_out;
  (* src = "test_simple.v:14.6-14.11" *)
  wire not_a;
  (* src = "test_simple.v:16.6-16.11" *)
  wire or_bc;
  (* src = "test_simple.v:17.6-17.16" *)
  wire xor_result;
  (* src = "test_simple.v:27.1-29.4" *)
  DFF _0_ (
    .C(clk),
    .D(xor_result),
    .Q(dff_out)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "test_simple.v:22.17-22.22|simple_map.v:2.44-2.83" *)
  AND _1_ (
    .A(a),
    .B(b),
    .Y(and_ab)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "test_simple.v:23.16-23.21|simple_map.v:3.42-3.81" *)
  OR _2_ (
    .A(b),
    .B(c),
    .Y(or_bc)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "test_simple.v:24.21-24.35|simple_map.v:4.44-4.83" *)
  XOR _3_ (
    .A(and_ab),
    .B(or_bc),
    .Y(xor_result)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "test_simple.v:32.15-32.30|simple_map.v:2.44-2.83" *)
  AND _4_ (
    .A(not_a),
    .B(dff_out),
    .Y(out1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "test_simple.v:21.16-21.18|simple_map.v:1.41-1.73" *)
  NOT _5_ (
    .A(a),
    .Y(not_a)
  );
  assign out2 = dff_out;
endmodule
